#!/usr/bin/env bash
killall -9 picom dunst 

exec feh --bg-fill feh --bg-fill /home/luc/.local/share/wall/wall-01.jpg
## Start Compositing Manager
exec picom &
## Notification Daemon
exec dunst &
## Notification low battery
bash ~/.config/dunst/scripts/low_bat_notifier.sh

## polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/bin/lxpolkit &
fi
